# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Start with a base image with Node.js and Bun installed
FROM jarredsumner/bun:edge as builder

# Set the working directory in the container
WORKDIR /app

# Copy the package.json and bun.lockb to the working directory
COPY package.json bun.lockb /app/

# Install dependencies
RUN bun install

# Copy the rest of the application source code to the working directory
COPY . .

# Build the project using Bun
RUN bun run build

# Use a lighter image for the runtime
FROM node:20-slim

# Set the working directory in the container
WORKDIR /app

# Copy the built files from the builder stage
COPY --from=builder /app/dist /app/dist

# Install production dependencies
RUN npm install --production

# Expose any necessary ports (if needed, e.g., 8080 for web servers)
# EXPOSE 8080

# Start the MCP server
ENTRYPOINT ["node", "/app/dist/main.js"]
